version: '3'
services:
  expressjs-api:
    container_name: expressjs-api
    tty: true
    build:
      context: .
      dockerfile: ./src/Dockerfile
    networks:
      - expressjs-network
    ports:
      - "3000:3000"

networks:
  expressjs-network:
    driver: "bridge"
