name: Expressjs-API

on:
  push:
    branches: [ "main" ]
  
jobs:
  Expressjs-API-Build-Tag-Push:
    runs-on: ubuntu-latest
    steps:
    
  # Checkout "femi-olaniran-IS27-devops-specialist-competition-req99120" Github Repository
      - name: Checkout Github Repository
        uses: actions/checkout@v3
   
   # Login to DockerHub Image Repository
      - name: Login to DockerHub
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      
   # Build the Expressjs API Application Image via docker-compose
      - name: Build the Docker image
        run: |
          docker-compose build expressjs-api
      
   # TROUBLESHOOTING - view images present in github action run
      - name: Docker List Images
        run: |
          docker image ls 
      
  # Tag Docker Image built with latest
      - name: Docker Tag Version
        run: |
          docker tag femi-olaniran-is27-devops-specialist-competition-req99120_expressjs-api ${{ secrets.DOCKERHUB_USERNAME }}/expressjs-api:latest

  # Push docker image to DockerHub Repository  
      - name: Docker Push Version
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/expressjs-api:latest


